runtime! debian.vim
set nocompatible
filetype off


" Splashscreen
set shortmess=I

syntax on
set nu
set smartindent
set softtabstop=4
set shiftwidth=4
set expandtab

set encoding=utf-8

" Always show the status line
set laststatus=2

" Format the status line
set statusline=%F%m%r%h\ %w\ \ CWD:\ %r%{getcwd()}%h\ \ \ Line:\ %l/%L\ %P

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
call vundle#end()
filetype plugin indent on

" C++ syntax in *.ino and *.pde files (Arduino)
autocmd BufNewFile,BufReadPost *.ino,*.pde set filetype=cpp

" Markdown syntax in *.md files
autocmd BufNewFile,BufReadPost *.md set filetype=markdown

" Set paste toggle
set pastetoggle=<F8>

colo slate
